steps:
  # Install dependencies
  - name: node:20-alpine
    entrypoint: npm
    args: ['ci']
    dir: '.'

  # Build the React application
  - name: node:20-alpine
    entrypoint: npm
    args: ['run', 'build']
    dir: '.'
    env:
      - 'VITE_API_URL=https://ai-rookie-774363048882.europe-north1.run.app/api'

  # Deploy to Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Upload all files to bucket
        gsutil -m cp -r dist/* gs://ai-rookie-frontend-$PROJECT_ID/
        
        # Set main page and error page
        gsutil web set -m index.html -e index.html gs://ai-rookie-frontend-$PROJECT_ID
        
        # Make bucket publicly readable
        gsutil iam ch allUsers:objectViewer gs://ai-rookie-frontend-$PROJECT_ID

  # Optional: Invalidate CDN cache if using Cloud CDN
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'compute'
      - 'url-maps'
      - 'invalidate-cdn-cache'
      - 'ai-rookie-frontend-lb'
      - '--path'
      - '/*'
      - '--async'
    # This step will fail if CDN is not set up, but that's ok

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '600s'